<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_AT1K4_SOLID" Id="{ea78c8b5-92ba-4f6a-a34a-74754b259467}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_AT1K4_SOLID
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// M26, Axis 26
// M27, Axis 27
// M28, Axis 28
// M29, Axis 29]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>