IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/v0.1.7
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = plc-kfe-motion
PROJECT_PATH := ../../plc-kfe-motion/plc-kfe-motion.tsproj
PLC = kfe_motion

PREFIX = PLC:KFE:MOTION

include $(IOC_TOP)/iocBoot/templates/Makefile.base
